version: "3.9"
services:
  postgres:
    image: postgres:15
    env_file: ./.env.api.docker
  redis:
    image: redis:7
  app:
    build: ./server
    env_file: ./.env.api.docker
    ports:
      - "${API_PORT}:3000"
    depends_on:
      - redis
      - postgres